// This file is automatically generated from your CSS. Any edits will be overwritten.
export const home: string;
export const phoneSection: string;
export const phoneContainer: string;
export const phone: string;
export const downloadBage: string;
