export const PLAYER_CONNECTED = 'PLAYER_CONNECTED';
export const GAME_LOADED = 'GAME_LOADED';
export const GAME_STATE_CHANGE = 'GAME_STATE_CHANGE';
export const QUIT_GAME = 'QUIT_GAME';
export const SET_PLAYER_ID = 'SET_PLAYER_ID';
export const SET_LOBBY_ID = 'SET_LOBBY_ID';